### ISSUE TITLE
unable to generate the zero_generate_list file

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/papers#3]
how to generate zero_generate_list , when i want to run build-vmap.py ? could you give me a example ?
Thanks in advance !!!
![image](https://user-images.githubusercontent.com/10346684/143438869-ed82681c-05d7-4356-b320-4581d576eeff.png)

**Comment by guillaumekln** [comment]
I updated the README and the scripts to clarify how to build the vmap. In particular, this zero_generate_list can be generated from `build-vmap.py` so I made it optional.

Please get the latest version and check the example in the README:

https://github.com/OpenNMT/papers/tree/master/WNMT2018/vmap#building-a-vmap

**Comment by Andrewlesson** [comment]
> I updated the README and the scripts to clarify how to build the vmap. In particular, this zero_generate_list can be generated from `build-vmap.py` so I made it optional.
> 
> Please get the latest version and check the example in the README:
> 
> https://github.com/OpenNMT/papers/tree/master/WNMT2018/vmap#building-a-vmap

Hello，I followed the instructions you gave, and the following problems occurred，this is part of phrase-table.gz below:

▁ 亓 ▁537 ||| ▁可 ||| 7.37077e-07 9.02505e-13 1 0.17503 ||| 2-0 ||| 1.35671e+06 1 1 ||| |||
▁ 亓 ▁969 ||| ▁我 ||| 9.79749e-08 5.34435e-12 1 0.853464 ||| 2-0 ||| 1.02067e+07 1 1 ||| |||
▁ 亓 ▁和 ||| ▁ ||| 2.21452e-07 2.17882e-10 1 0.0714794 ||| 0-0 1-0 2-0 ||| 4.51565e+06 1 1 ||| |||
▁ 亓 ▁姐 ||| ▁他 ||| 4.79902e-07 1.90102e-14 1 0.005767 ||| 1-0 ||| 2.08376e+06 1 1 ||| |||
▁ 亓 ▁官 ||| ▁ ||| 2.21452e-07 3.62348e-12 1 0.212946 ||| 0-0 ||| 4.51565e+06 1 1 ||| |||
▁ 亓 ▁按 ||| ▁ 亓 ||| 0.00943396 1.44836e-06 1 0.00933327 ||| 0-0 1-1 ||| 106 1 1 ||| |||
▁ 亓 ▁桃 ||| ▁陶 ▁桃 ||| 0.333333 1.13374e-08 1 0.000586505 ||| 1-0 0-1 2-1 ||| 3 1 1 ||| |||
▁ 亓 ▁演 ||| ▁ ||| 2.21452e-07 6.99533e-12 1 0.212946 ||| 0-0 ||| 4.51565e+06 1 1 ||| |||
▁ 亓 ▁炳 ||| ▁ 亓 ▁炳 ||| 1 0.00167382 1 0.00148626 ||| 0-0 1-1 2-2 ||| 1 1 1 ||| |||
▁ 亓 ▁那 ||| ▁ 亓 ||| 0.00943396 2.75102e-05 1 0.00933327 ||| 0-0 1-1 ||| 106 1 1 ||| |||
▁ 亖 ||| ▁ ||| 2.21452e-07 0 0.5 0.212946 ||| 0-0 ||| 4.51565e+06 2 1 ||| |||
▁ 亖 ||| ▁ 醯 ||| 0.0212766 0.00158313 0.5 0.00204767 ||| 0-0 0-1 1-1 ||| 47 2 1 ||| |||
▁ 亖 ▁弄 ||| ▁ 醯 ||| 0.0212766 3.4908e-07 1 0.00204767 ||| 0-0 0-1 1-1 ||| 47 1 1 ||| |||
▁ 亖 ▁给 ||| ▁ ||| 2.21452e-07 0 1 0.212946 ||| 0-0 ||| 4.51565e+06 1 1 ||| |||
▁ 亙 ||| ▁ ||| 2.21452e-07 0 1 0.212946 ||| 0-0 ||| 4.51565e+06 1 1 ||| |||
▁ 亙 ▁古 ||| ▁ ||| 2.21452e-07 0 1 0.212946 ||| 0-0 ||| 4.51565e+06 1 1 ||| |||
▁ 亜 ||| ▁ ||| 2.21452e-07 0 0.333333 0.212946 ||| 0-0 ||| 4.51565e+06 3 1 ||| |||
▁ 亜 ||| ▁ 亜 ||| 0.0555556 0.0163397 0.666667 0.0166364 ||| 0-0 1-1 ||| 36 3 2 ||| |||
▁ 亜 ▁姨 ||| ▁ ||| 2.21452e-07 0 1 0.212946 ||| 0-0 ||| 4.51565e+06 1 1 ||| |||

[@bllz_132_694 vmap]# python2 build-vmap.py -pt phrase-table.gz 1> /dev/null 2> zg.txt
[@bllz_132_694 vmap]# cat zg.txt 
Traceback (most recent call last):
  File "build-vmap.py", line 26, in <module>
    with open(args.zero_generate_list, "rb") as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found

[@bllz_132_694 vmap]# python2 build-vmap.py -pt phrase-table.gz  -ms 3 -mf 2 -km 20 -tv target_vocabulary -zg zg.txt > vmap
Traceback (most recent call last):
  File "build-vmap.py", line 49, in <module>
    for v in entries[1].split(" "):
IndexError: list index out of range

[@bllz_132_694 vmap]# rm -rf vmap.txt zg.txt
[@bllz_132_694 vmap]# python2 build-vmap.py -pt phrase-table.gz -zg zg.txt 1> vmap.txt 2> /dev/null
[@bllz_132_694 vmap]# cat vmap.txt 

these are no result display
